name: C++ CI

on: 
  push:
    paths:
      - 'src/**'
      - 'include/**'
      - 'CMakeLists.txt'
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release]
        use_asan_and_ubsan: [ON, OFF]

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            ccache \
            libsfml-dev \
            libfreetype6-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libudev-dev \
            libopenal-dev \
            libvorbis-dev \
            libflac-dev

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # v1.2.23
        with:
          key: ${{ runner.os }}-${{ matrix.build_type }}-${{ matrix.use_asan_and_ubsan }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.build_type }}-
          max-size: 2G

      - name: Run vcpkg
        uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 #v11.6
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure CMake
        run: >
          cmake -B build -G Ninja
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DENABLE_SANITIZERS=ON
          -DASAN_UBSAN=${{ matrix.use_asan_and_ubsan }}
          -DBUILD_WITH_TRACY=OFF

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure
